### ISSUE TITLE
Issue with Z-up coordinate system.

### ISSUE THREAD

**Issue by hunterZh37** [artcom/react-three-arjs#4] opened 2022-01-09 20:43 UTC
The coordinate system of the meshes I want to render is set as a Z-up coordinate system. Three.js, ar.js and react-three-arjs assume a Y-up coordinate system.  Our application scenario assumes a z-up coordinate system, so we customized our setup within three.js by tweaking the camera and specifying Y-up in each node in the scene. However, our attempt does not seem to play nicely with ar.js and react-three-arjs. For example, if I set the camera = {{up : [0,0,1]}} in ARCanvas, the transforms applied to the meshes will be rendered incorrectly in the ARScene.

**Comment by j-era** [comment] 2022-01-24 11:48
Hi @hunterZh37, first thank you for our first issue :) This is not our full-time projekt, so sorry for the late response. Could you provide an example/ screenshot showing the incorrect rendering? I can imagine that the error is also related to https://github.com/AR-js-org/AR.js/issues/230

**Comment by kalwalt** [comment] 2022-03-07 19:13
> Hi @hunterZh37, first thank you for our first issue :) This is not our full-time projekt, so sorry for the late response. Could you provide an example/ screenshot showing the incorrect rendering? I can imagine that the error is also related to [AR-js-org/AR.js#230](https://github.com/AR-js-org/AR.js/issues/230)

Hi @j-era @hunterZh37 recently i did some changes in AR.js that i think fixed that issue can you update the project and tell me if the issue is solved? 
Note that i will merge soon the dev branch into master too.
Thank you :smile:

**Comment by j-era** [comment] 2022-03-08 09:13
Hi @kalwalt we tested with 3.3.3-es6-beta-04 (https://codesandbox.io/s/jolly-hodgkin-ssu33). Unfortunately, the error still occurs on mobile devices. On desktop it works fine.

![test](https://user-images.githubusercontent.com/4621891/157203928-37ebdc5f-6fd9-4f9b-9325-b9b4620de50f.jpg)

**Comment by kalwalt** [comment] 2022-03-08 09:48
> Hi @kalwalt we tested with 3.3.3-es6-beta-04 (https://codesandbox.io/s/jolly-hodgkin-ssu33). Unfortunately, the error still occurs on mobile devices. On desktop it works fine.
> 
> ![test](https://user-images.githubusercontent.com/4621891/157203928-37ebdc5f-6fd9-4f9b-9325-b9b4620de50f.jpg)
> 

Hi @j-era i forgot to say that is needed to provide the orientation value as in the AR.js examples, answering from my Mobile device quite hard to point to One example, but i will try to open and issue an maybe a PR to fix this.🙂

**Comment by kalwalt** [comment] 2022-03-09 23:46
working on this my branch https://github.com/kalwalt/react-three-arjs/tree/testing-arjs-3.4.0-alpha-rc1. As a reference look at https://github.com/AR-js-org/AR.js/blob/master/three.js/examples/basic.html

**Comment by j-era** [comment] 2022-03-30 10:27
Thank you @kalwalt ! Found time to fix this https://github.com/artcom/react-three-arjs/commit/76f3f1b2ec5210bf6830599d2669ac4994c51111

**Comment by kalwalt** [comment] 2022-03-30 12:23
> Thank you @kalwalt ! Found time to fix this [76f3f1b](https://github.com/artcom/react-three-arjs/commit/76f3f1b2ec5210bf6830599d2669ac4994c51111)

That's perfect! Have you a live example to test?

**Comment by j-era** [comment] 2022-03-30 13:42
> 

Yes, updated https://codesandbox.io/s/jolly-hodgkin-ssu33

**Comment by kalwalt** [comment] 2022-03-30 22:31
@j-era i tested your example but on my device it doesn't worked well. The app can not constantly detect the hiro marker. I note also that you are using an older version of ar.js ltest is `3.4.0-alpha-rc2`

**Comment by j-era** [comment] 2022-03-31 07:27
> @j-era i tested your example but on my device it doesn't worked well. The app can not constantly detect the hiro marker. I note also that you are using an older version of ar.js ltest is `3.4.0-alpha-rc2`

Thanks for testing! Ok, strange, did you see I'm working on the branch `update-arjs`? ([ar.js version is 3.4.0-alpha-rc2](https://github.com/artcom/react-three-arjs/blob/feature/update-arjs/package.json#L42))
Worked fine on my device, but i will do some more tests on different mobiles.

**Comment by j-era** [comment] 2022-03-31 07:43
@kalwalt Which browser did you use for testing? Mobile Chrome (Android) works fine on my device, but I can see the issue you described with Firefox (both Desktop and Mobile)

**Comment by kalwalt** [comment] 2022-03-31 09:34
I tested on my Oppo A72 with Android 11 and Chrome browser. I will try again with Firefox too. Now i see the new branch, that's fine! 🙂

**Comment by j-era** [comment] 2022-05-02 13:42
@hunterZh37 Closing this because #10 has been resolved. Hopefully it solves your issue!

**Closed by j-era** 2022-05-02 13:42 UTC

**Comment by sinano1107** [comment] 2022-06-27 08:03
> @hunterZh37 Closing this because #10 has been resolved. Hopefully it solves your issue!

I am the one who created #10.
The reason I closed the issue is because I didn't think it was desirable to have multiple duplicate issues.
So the issue has not actually been resolved.
